### PR TITLE
added uozcan12 profile

### PR DESCRIPTION
**Pull request by uozcan12**

### CODE REVIEW

**Review by softcreations01 — APPROVED** [review]

**Review by softcreations01 — CHANGES_REQUESTED** [review]
The code contains conflicting issue

**Comment by softcreations01** [comment]
Resolve index.hml and style.css file card number

**Review by softcreations01 — APPROVED** [review]

**Comment by softcreations01** [comment]
Now okay

**Comment by uozcan12** [comment]
Thank you @softcreations01 ☺️ Can you add “hacktoberfest-accepted” label to my PR? Thank you🙏

**Pull request merged**
